### ISSUE TITLE
NoCredentialsError: Unable to locate credentials on `xr.open_dataset(s3_uri, engine="zarr")`

### ISSUE THREAD

**Issue by milancurcic** [sofarocean/spotter-data-archive#3]
Hi,

I'm now getting to making an example of using [CloudDrift](https://github.com/Cloud-Drift/clouddrift) with Spotter data.

I'm getting a `NoCredentialsError: Unable to locate credentials` on

```
s3_uri = "s3://sofar-spotter-archive/spotter_data_bulk_zarr/"
ds = xr.open_dataset(s3_uri, engine="zarr")
```

in the `plot_spotter_bulk_data` notebook.

Does the dataset have anon access? It used to have a few weeks ago.

Thanks!

**Comment by milancurcic** [comment]
The error goes away and the dataset opens correctly if I set `s3_uri` to the full HTTPS URL:

```
s3_uri = "https://sofar-spotter-archive.s3.amazonaws.com/spotter_data_bulk_zarr"
```

**Comment by isabelhoughton** [comment]
Updated in the example scripts.
